create table Measurement_Unit
(
    id            integer generated by default on null as identity,
    label         varchar(25) not null,
    singular_name varchar(50) not null,
    plural_name   varchar(50) not null,
    constraint pk_Measurement_Unit primary key (id)
)
