create table Company
(
    id       integer generated by default on null as identity,
    name     varchar(100) not null,
    place_id integer,
    constraint pk_Company primary key (id),
    constraint uc_Company_name_place unique (name, place_id),
    constraint fk_Company_Place foreign key (place_id) references Place (id)
)
