create table Article_Image
(
    article_id integer       not null,
    id         integer generated by default on null as identity,
    image_url  varchar(2083) not null,
    constraint pk_Article_Image primary key (article_id, id),
    constraint uc_Article_Image unique (article_id, image_url),
    constraint fk_Article_Image_Article foreign key (article_id) references Article (id) on delete cascade
)
