create table Category
(
    id          integer generated by default on null as identity,
    name        varchar(50) not null,
    description clob,
    constraint pk_Category primary key (id),
    constraint uc_Category_name unique (name)
)
