create table Place
(
    id             integer generated by default on null as identity,
    country_id     integer not null,
    admin_area     varchar(100),
    locality       varchar(100),
    postal_code    varchar(15),
    street_address varchar(150),
    constraint pk_Place primary key (id),
    constraint fk_Place_Country foreign key (country_id) references Country (id),
    constraint uc_Place_Location unique (locality, postal_code, street_address)
)
