create table Company
(
    id         integer generated by default on null as identity,
    short_name varchar(100) not null,
    long_name  varchar(100) not null,
    place_id   integer,
    constraint pk_Company primary key (id),
    constraint uc_Company_name_place unique (short_name, long_name, place_id),
    constraint fk_Company_Place foreign key (place_id) references Place (id)
)
